# On part de l'image officielle de Jenkins
FROM jenkins/jenkins:lts

# On passe en utilisateur administrateur (root) pour pouvoir installer des paquets
USER root

# Installation du client Docker, Python et Pip
RUN apt-get update && \
    apt-get install -y docker.io python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/*

# On reste délibérément en utilisateur root pour ce TP
# Cela évitera les problèmes de permissions "Permission denied"
# au moment de lire le fichier docker.sock de ta machine hôte.