# On part de l'image officielle de Jenkins
FROM jenkins/jenkins:lts

# On passe en root pour installer le client Docker
USER root

# On installe UNIQUEMENT le client Docker CLI
# Python et sonar-scanner tournent dans leurs propres conteneurs via le pipeline
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Pré-installation des plugins nécessaires au démarrage
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

# On reste en root pour l'accès au socket Docker de l'hôte
