# Project identification
sonar.projectKey=mon-app-python
sonar.projectName=Mon App Python
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=.
sonar.exclusions=**/test_*.py,**/tests/**

# Path to test directories
sonar.tests=.
sonar.test.inclusions=**/test_*.py

# Language
sonar.language=py
sonar.python.version=3

# Encoding of the source code
sonar.sourceEncoding=UTF-8
