---
- name: "Vérification du déploiement"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    image_name: "loueysioua/mon-app-devops"
    image_tag:  "latest"
    app_port:   8081

  tasks:

    - name: "Attente que l'application réponde sur /health"
      uri:
        url: "http://localhost:{{ app_port }}/health"
        method: GET
        status_code: 200
        timeout: 5
      register: health_result
      retries: 10
      delay: 3
      until: health_result.status == 200

    - name: "Résumé du déploiement"
      debug:
        msg: "✅ Déploiement OK — {{ image_name }}:{{ image_tag }} répond sur http://localhost:{{ app_port }}"
