# ansible/inventory/hosts.ini
# Pour un déploiement K8s, on pilote depuis localhost (connexion directe via kubectl)

[local]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
